services:
  PrestaShop\Module\PrestashopFacebook\Dispatcher\EventDispatcher:
    class: PrestaShop\Module\PrestashopFacebook\Dispatcher\EventDispatcher
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ApiConversionHandler'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\PixelHandler'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Provider\EventDataProvider'
      - '@ps_facebook.context'
