services:
  PrestaShop\Module\Ps_facebook\Tracker\Segment:
    class: 'PrestaShop\Module\Ps_facebook\Tracker\Segment'
    public: true
    arguments:
      - '@ps_facebook.context'
      - '@PrestaShop\Module\PrestashopFacebook\Config\Env'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
